root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server ."
  bin = "./tmp/server"
  include_ext = ["go"]
  exclude_dir = ["tmp"]
  delay = 500
  stop_on_error = true

[log]
  time = true
